name: plogger
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-129.0.dev <4.0.0'

dependencies:
  camera: ^0.10.5+2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_login: ^4.1.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  http: ^1.0.0
  pedometer: ^4.0.0
  permission_handler: ^10.3.0
  sensors_plus: ^3.0.2
  vibration: ^1.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
