// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF4HkAGl3Q0CaB7Rh43dc9PbnNROHAzf8',
    appId: '1:940909690947:web:49d2ee4b4f78ee3dc294f6',
    messagingSenderId: '940909690947',
    projectId: 'plogger-0235',
    authDomain: 'plogger-0235.firebaseapp.com',
    storageBucket: 'plogger-0235.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD89evkfVabfX5zwL_hwO-WHNtQ5_arB2E',
    appId: '1:940909690947:android:9e1f5aa48c1e3cddc294f6',
    messagingSenderId: '940909690947',
    projectId: 'plogger-0235',
    storageBucket: 'plogger-0235.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnmKdk2Fv9h2ACq5RRw1GHdVWR_zXanlc',
    appId: '1:940909690947:ios:2f6024d08d359004c294f6',
    messagingSenderId: '940909690947',
    projectId: 'plogger-0235',
    storageBucket: 'plogger-0235.appspot.com',
    androidClientId: '940909690947-hk9lek4jqqj79shd1c8lur4cl23gne4a.apps.googleusercontent.com',
    iosClientId: '940909690947-fskomdk0mp3f5dqvdp03c78j2seau3dl.apps.googleusercontent.com',
    iosBundleId: 'com.example.plogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnmKdk2Fv9h2ACq5RRw1GHdVWR_zXanlc',
    appId: '1:940909690947:ios:8d5e7bad1f93fbd2c294f6',
    messagingSenderId: '940909690947',
    projectId: 'plogger-0235',
    storageBucket: 'plogger-0235.appspot.com',
    androidClientId: '940909690947-hk9lek4jqqj79shd1c8lur4cl23gne4a.apps.googleusercontent.com',
    iosClientId: '940909690947-bvh4k56or9sma3i2hbr1looasmaokrb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.plogger.RunnerTests',
  );
}
